export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $bunnerSlider: document.querySelector('.banner-slider'),
  $marketing: document.querySelector('.marketing'),
  $catalogSlider : document.querySelector('.hero-catalog__slider'),
  $catalogFiltersTop: document.querySelectorAll('.catalog-filter__top'),
  $hideFilters: document.querySelector('.hide-filters'),
  $catalogColumns: document.querySelector('.catalog-columns__list'),
  $catalogGridContent: document.querySelector('.catalog-grid__content'),
  $catalogFilterItems: document.querySelectorAll('.catalog-filter__item'),
  $catalogChoice: document.querySelector('.catalog-choice'),
  $freeDeliveryBtn: document.querySelector('.free-delivery__btn'),
  $customSelect: document.querySelectorAll('.custom-select'),
  $cardSliderThumbs: document.querySelectorAll('.card-slider__thumb'),
  $colorSelect: document.querySelector('.color-select__list'),
  $sizeSelect: document.querySelector('.size-select__list'),
  $stepper: document.querySelector('.stepper'),
  $cardDescription: document.querySelector('.card-description'),
  $cardRelatedSlider: document.querySelector('.card-related__slider'),
  $toTop: document.querySelector('.to-top'),
  $burger: document.querySelector('.burger'),
  $navClose: document.querySelector('.nav__close'),
  $nav: document.querySelector('.nav'),
  $filtersOpenMobile: document.querySelector('.filters-open-mobile'),
  $catalogFilters: document.querySelector('.catalog-filters'),
}
